name = "cardday"
main = "src/index.js"
compatibility_date = "2026-04-27"

[triggers]
crons = ["0 0 * * *", "0 9 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "cardday-db"
database_id = "ef783458-14f2-4c72-8dde-9f0314b85667"
